### PR TITLE
doc: fix option tables

### PR DESCRIPTION
**Pull request by guilhem**

### CODE REVIEW

**Review by ofek — CHANGES_REQUESTED** [review]
What is the issue?

**Comment by maennchen** [comment]
Looks fine here for me: https://ofek.dev/csi-gcs/static_provisioning/

@guilhem Did you look at the docs here in GitHub or in the deployed documentation?

**Comment by maennchen** [comment]
@guilhem Is this still relevant?

**Comment by maennchen** [comment]
@ofek I believe we can close this PR.

**Pull request closed without merging**
